### ISSUE TITLE
Error while running " wake 'runSim $(dut plan}' " .

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/block-pio-sifive#40]
I've been trying to get going with block-pio project. Firing the command `wake 'runSim {dut plan}'` as specified in Readme throws following error:

```
Was expecting an (OPERATOR/LAMBDA/ID/LITERAL/PRIM/POPEN), got a BOPEN at <command-line>:1:9
Was expecting a END, but got a BOPEN at <command-line>:1:9
Type error; function <command-line>:1:[1-8] expected argument 'argument' of type:
    RocketChipDUTPlan
  but was supplied argument src/parser.cpp:400:1 of type:
    String
>>> Aborting without execution <<<
```

The `runSim` executes the file `./api-generator-sifive/top.wake` script. 

How do I fix this?

**Comment by richardxia** [comment]
That line in the README was not intended to be copied literally onto the command line, and instead the `${dut plan}` was meant to be a cue to the reader to manually replace it with an instance of a "dut plan", such as `pioDUT` or `pio16DUT`, similar to a command line tool's [usage message](https://en.wikipedia.org/wiki/Usage_message).

I'll admit that the way the README has written this is not the most obvious, since it is easily mistaken for real code, so we should reword the README to make this clearer.

Sorry for the confusion that this may have caused.

**Comment by saurabhsingh-pvips** [comment]
Yes. It's confusing indeed. 
Anyways, the runSim command encounter yet another error:
```
<ivycache> ivycache
protoc --java_out=build/firrtl/proto firrtl/src/main/proto/firrtl.proto
execve protoc: No such file or directory
WARNING: Could not parse DTS JSON: _root_.sifive.skeleton.DefaultConfig_sifive.skeleton.WithSimUART_sifive.skeleton.WithTestFinisher_sifive.blocks.pio.WithpioTop.json file not found
PANIC: Error "File not found" Nil
Requirement !panic_called failed at src/exception.cpp:64
```
Google look up suggest Missing [protobuf](https://github.com/protocolbuffers/protobuf/blob/master/src/README.md) but reinstalling protobuf doesn't help. Warning persists.

It appears to me as if the `build.wake` in `soc-testsocket-sifive` fails to import the `WithpioTop..json` file or the file is missing. Help?

**Comment by richardxia** [comment]
@saurabhsingh-pvips, could you submit a separate ticket describing this new issue. It is unrelated to the previous issue, and it'll make it better for future searchability if we keep each issue focused on only the issue at hand.
