### ISSUE TITLE
wake 'runSimWith pioDUT Verilator' fails.

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/block-pio-sifive#43]
I've been trying to get through with the pio-block example.

Firing the command `wake 'runSimWith pioDUT Verilator' ` fails with a lot of warnings. I don't think putting everything up here would make sense. Uploading the `config.log` from `workspace/build/freedom-metal/pioDUT/`. [config.log](https://github.com/sifive/block-pio-sifive/files/3872966/config.log)
I see a couple of `fatal errors` from line 70.

How can I zero in on the actual problem? Any more logs to help me in debugging? The simulation did mention two files `std.err & std.out` but I fail to find them.

How do I fix this?

**UPDATE:**

![image](https://user-images.githubusercontent.com/57518239/69235528-9ed68100-0bb7-11ea-9096-e01d4d644fa6.png)

I am not sure if Verilator is been selected. Why is `+perl +incdir+api-generator-sifive/vsrc` vcs being selected over here?

**Comment by richardxia** [comment]
Hi @saurabhsingh-pvips, I am not sure if the two different things you mentioned are related. While I don't know what the expected behavior is for the `freedom-metal` `config.log` file is, I don't think it is an error. That file appears to contain the console output from running [`./configure`](https://en.wikipedia.org/wiki/Configure_script), which will perform many checks about the tools installed on a machine to see if all the necessary dependencies for compiling the program are available. I think the failed checks, such as the `g++ -V` call are just alternative ways of querying the installed executables, since not all implementations of tools support the same command line options.

Regarding the second error message, it looks like the command cannot find the Verilator executable. We should probably fix the Verilator wrapper script such that it errors earlier with a more meaningful error message if it cannot locate Verilator. To answer your question of why `perl` is invoked, it's because the entrypoint to Verilator is actually a Perl script.

The reason for your error is probably due to the fact that Wake executes in a sandboxed environment, and tools must be explicitly passed into Wake. This is the exact same thing that @jackkoenig explained in https://github.com/sifive/block-pio-sifive/issues/42#issuecomment-555867896, but you'll need to apply that to the Verilator executable this time.

**Comment by saurabhsingh-pvips** [comment]
Okay!

I tried to repeat the steps mentioned in #42 as you suggested but failed to do so. I am not able to replicate the steps to Verilator. Can you help me with this?

**Comment by richardxia** [comment]
Can you describe what steps you took, and what outcome you ran into? I'm not sure I can help you without further information, as I would just recommend that you follow the steps again, so I need more information on what you tried doing and what didn't work.

**Comment by saurabhsingh-pvips** [comment]
I am trying to solve this error regarding gcc:

`configure:2921: gcc -march=rv64imafdc -mabi=lp64d -g -mcmodel=medany   conftest.c  >&5
gcc: error: unrecognized argument in option '-mabi=lp64d'
gcc: note: valid arguments to '-mabi=' are: ms sysv
gcc: error: unrecognized argument in option '-mcmodel=medany'
`
The issue mentioned [here](https://github.com/riscv/riscv-tools/issues/79#issue-230397958) is similar to the issue I've encountered in the config.log
[config.log](https://github.com/sifive/block-pio-sifive/files/3939850/config.log)
The fix mentioned is to use CROSS_COMPILE switch. But I am not sure where to use this switch n how.

**Comment by albertchen-sifive** [comment]
It looks like wake cannot find a riscv-toolchain which is why `configure` is trying to use `gcc` rather than `riscv64-unknownelf-gcc`. in wake we use environment-packages to abstract away environment details like where tools are installed. you can see the example environment for more details https://github.com/sifive/environment-example-sifive. you can also take a look at this PR to environment-blockci-sifive for an example of how to use the example environment to set tell wake where riscv-tools is installed https://github.com/sifive/environment-blockci-sifive/pull/5/files.

**Comment by saurabhsingh-pvips** [comment]
Yes, this worked. The build is able to pass through this point!
