### ISSUE TITLE
"execve gem: No such file or directory" for 'wake makeOnboardingDocument pioDUT'.

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/block-pio-sifive#59]
I am experiencing a rather strange deadlock between versions of ruby to create the preonboarding document.

Installed Ruby using `apt-get install ruby`. The `wake makeOnboardingDocument pioDUT` finishes but `asciidoctor-pdf` to convert .adoc to .pdf fails for following reason.
Error: allow-uri read is not enabled. See [here](https://github.com/asciidoctor/asciidoctor-pdf/issues/1423)
Effect: The svg file is printed directly and is not converted to image in the final document.
Fix: To install 'asciidoctor-pdf' using git repo. See [here](https://github.com/asciidoctor/asciidoctor-pdf/issues/1423)

The readme of above repo mentions to use `RVM` to install and manage Ruby. You can find installation steps [here](https://github.com/rvm/ubuntu_rvm) & [here](https://rvm.io/rvm/install).

Ruby is succesfully installed and set up. Now the `wake makeOnboardingDocument pioDUT` fails with error:
```
gem install bundler -v '>=2' --install-dir build/scribble/.gem
execve gem: No such file or directory
Fail (Error "Scribble failed to produce output file build/api-generator-sifive/pioDUT/documents/pioDUT.adoc" Nil)
```
I've tried with ruby `v2.3.7(the minimum required), v2.5.7(this version same as when installed using `apt-get install ruby` and v2.6.3 (the latest version)` & gem `v2.7.7` & `v3.0.3` but of no use. Also tried adding path in env.json as done with protoc, verilator & riscv gnu-toolchain but of no use.

**Comment by richardxia** [comment]
/cc @john-sifive, @albertchen-sifive, and @jackkoenig 

This is likely due to Wake not being able to see the `gem` executable that you are using. When Wake runs, it intentionally runs in a sandboxed environment where most environment variables are not inherited from the caller.

https://github.com/sifive/environment-example-sifive is an example of how you can set up your own Wake environment package that publishes the paths to specific tools. The specific version of Ruby that we have been testing against is Ruby 2.5, which you can see is used [here](https://github.com/sifive/api-languages-sifive/blob/f26c8d18045cfa15b5f8d92b2930da3b4cb8d048/ruby.wake#L70), so you'll want to create an entry in your environment package that exports the path to both `ruby` and `gem`.

**Comment by saurabhsingh-pvips** [comment]
As mentioned earlier, I did try adding paths to environment package. Still, I did fresh installation of 2.5.1 and added paths to both Ruby & Gem as per my system:

`which ruby`
`/usr/share/rvm/rubies/ruby-2.5.1/bin/ruby`

`which gem`
`/usr/share/rvm/rubies/ruby-2.5.1/bin/gem`

Packages added in `environment-example-sifive/env.json`
 ```
"ruby": {"2.5.1":{"PATH":"/usr/share/rvm/rubies/ruby-2.5.1/bin"}},
"gem": {"2.7.7":{"PATH":"/usr/share/rvm/rubies/ruby-2.5.1/bin"}},
```
The build still fails at `execve gem: No such file or directory`.
Am I doing anything wrong?

Also, no issue related to path of ruby or gem is encountered when ruby is installed using `apt-get install`.

**Comment by richardxia** [comment]
Your env.json will probably need to look closer to this:

```json
"ruby": {"ruby": {"2.5.1":{"PATH":"/usr/share/rvm/rubies/ruby-2.5.1/bin"}}}
```

There should be a second `ruby` key, since the resource string requested by the command is written `ruby/ruby/2.5.1`. Also, you don't need the `gem` key in your env.json because that executable should come from the same resource string `ruby/ruby/2.5.1`. The keys in the env.json file should correspond to the resource strings, which may not necessarily exactly match names of the actual executables.

**Comment by saurabhsingh-pvips** [comment]
Build moves from last error after applying the fix above but gets stuck immediately. 
Error: 
```
asciidoctor --out-file build/api-generator-sifive/pioDUT/documents/pioDUT.html build/api-generator-sifive/pioDUT/documents/pioDUT.adoc
/usr/bin/env: 'ruby': No such file or directory
Fail (Error "Scribble failed to produce output file build/api-generator-sifive/pioDUT/documents/pioDUT.adoc" Nil)
```
Looks like there are different environments? The one in which ruby is running i.e rvm's environment and this default one.

It's hard to recognize if this is some issue where rvm fails to link environments or is there issue with how we wake builds the environment?

How do I fix this?

`which env` : `/usr/bin/env`
`which ruby` : `/usr/share/rvm/rubies/ruby-2.5.1/bin/ruby`

**Comment by saurabhsingh-pvips** [comment]
Worked around the issue by installing ruby via apt-get. `which ruby` still returns `/usr/share/rvm/rubies/ruby-2.5.1/bin/ruby` but somehow it works with both the installations. Comments?
